# The SeriesThe series is the object of the pandas library designed to represent one-dimensional data structures, similar to an array but with some additional features

# Series creation in pandas

In [1]:
import pandas as pd
series_data=pd.Series([0,1,2,3,4,5])

In [2]:
series_data

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

# seires creation with index name

In [3]:
series_data=pd.Series([0,1,2,3,4,5],index=['A','B','C','D','E','F'])

In [4]:
series_data

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64

# to know the shape,index and its values of a series

In [5]:
series_data.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [6]:
series_data.values

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [7]:
series_data.shape

(6,)

# Accessing the Internal Elements

In [13]:
series_data['F']

5

In [8]:
series_data[5]

5

In [9]:
series_data[0:3]

A    0
B    1
C    2
dtype: int64

In [10]:
series_data[:3]

A    0
B    1
C    2
dtype: int64

modifying series values

In [11]:
series_data[3]=20

In [12]:
series_data

A     0
B     1
C     2
D    20
E     4
F     5
dtype: int64

# filtering values in a series data

In [14]:
sd=pd.Series([83,86,89,90,82],index=['Tamil','English','Maths','Sceince','Socialscience'])

In [15]:
sd>82

Tamil             True
English           True
Maths             True
Sceince           True
Socialscience    False
dtype: bool

In [18]:
sd1=sd[sd>82]

In [19]:
sd1

Tamil      83
English    86
Maths      89
Sceince    90
dtype: int64

In [20]:
total=sd.sum()

In [21]:
total

430

In [23]:
sd.mean()

86.0

In [25]:
sd.unique()

array([83, 86, 89, 90, 82], dtype=int64)

In [29]:
sd.value_counts()

86    1
82    1
83    1
90    1
89    1
dtype: int64

# To know all the values contained in the series, excluding duplicates,you can use the unique() function. The return value is an array containing the unique values in the series, although not necessarily in order.A function that’s similar to unique() is value_counts(),which not only returns unique values but also calculates the occurrences within a series


In [32]:
sd1=pd.Series([84,86,89,89,82],index=['Tamil','English','tamil','Sceince','Socialscience'])

In [33]:
sd1.value_counts()

89    2
86    1
84    1
82    1
dtype: int64

In [34]:
sd1.unique()

array([84, 86, 89, 82], dtype=int64)

In [35]:
sd

Tamil            83
English          86
Maths            89
Sceince          90
Socialscience    82
dtype: int64

In [38]:
sd.isin([83])

Tamil             True
English          False
Maths            False
Sceince          False
Socialscience    False
dtype: bool

# counting NaN values in a series

In [40]:
import numpy as np
s2 = pd.Series([5,-3,np.NaN,14]) 

In [41]:
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [42]:
s2.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [43]:
s2.isna().sum()

1

In [44]:
s2 = pd.Series([np.NaN,-3,np.NaN,14])
s2.isna().sum()

2

In [46]:
s2.notnull()

0    False
1     True
2    False
3     True
dtype: bool

In [49]:
sd

Tamil      87
English    81
Maths      89
Science    85
Social     86
dtype: int64

# Series as Dictionaries

In [47]:
sd=pd.Series({'Tamil':87,'English':81,'Maths':89,'Science':85,'Social':86})

In [48]:
sd

Tamil      87
English    81
Maths      89
Science    85
Social     86
dtype: int64

In [54]:
marks={'Tamil':87,'English':81,'Maths':89,'Science':85,'Social':86}
sd=pd.Series(marks,dtype=float)

In [55]:
sd

Tamil      87.0
English    81.0
Maths      89.0
Science    85.0
Social     86.0
dtype: float64

# As you can see from this example, the array of the index is filled with the keys while the data are filled with the corresponding values. You can also define the array indexes separately. In this case, controlling correspondence between the keys of the dict and labels array of indexes will run. If there is a mismatch, pandas will add the NaN value.

In [56]:
subjects=['Tamil','English','Maths','Science','Social','physics']
marks={'Tamil':87,'English':81,'Maths':89,'Science':85,'Social':86}
sd=pd.Series(marks,index=subjects,dtype=float)

In [57]:
sd

Tamil      87.0
English    81.0
Maths      89.0
Science    85.0
Social     86.0
physics     NaN
dtype: float64

In [61]:
tenth_marks={'Tamil':87,'English':81,'Maths':89,'Science':85,'Social':86}
sd1=pd.Series(tenth_marks)
twelth_marks={'Tamil':90,'English':87,'Maths':99,'Physics':88,'Chemistry':97,'Biology':97}
sd2=pd.Series(twelth_marks)
sd=sd1+sd2

In [62]:
sd

Biology        NaN
Chemistry      NaN
English      168.0
Maths        188.0
Physics        NaN
Science        NaN
Social         NaN
Tamil        177.0
dtype: float64

# the matched columns are added and other columns left with NaN 

# Unlike series, which have an index array containing labels associated with each element, the dataframe has two index arrays. 

The first index array, associated with the lines, has very similar functions to the index array in series. In fact, each label is associated with all the values in the row. 

The second array contains a series of labels, each associated with a particular column.

 A dataframe may also be understood as a dict of series, where the keys are the column names and the values are the series that will form the columns of the dataframe. Furthermore, all elements in each series are mapped according to an array of labels, called the index.


# Defining a Dataframe
The most common way to create a new dataframe is precisely to pass a dict object
to the DataFrame() constructor. This dict object contains a key for each column 
that you want to define, with an array of values for each of them.


# The pd.DataFrame( )

In [72]:

shopping_cart={
               'vegetables':['brinjal','potato','onion','tomato'],
               'vegetables_price':[20,40,35,26],
                'Sweets':['cake','biscuits','candy','lollypop'],
                 'Sweets_price':[25,45,30,25],
                'Fruits':['Apple','Orange','banana','Cherry'],
                 'Fruits_price':[30,45,60,90]                    
              }
data=pd.DataFrame(shopping_cart,index=['item1','item2','item3','item4'])

In [73]:
data

vegetables  vegetables_price    Sweets  Sweets_price  Fruits  \
item1    brinjal                20      cake            25   Apple   
item2     potato                40  biscuits            45  Orange   
item3      onion                35     candy            30  banana   
item4     tomato                26  lollypop            25  Cherry   

       Fruits_price  
item1            30  
item2            45  
item3            60  
item4            90

In [77]:
data.index

Index(['item1', 'item2', 'item3', 'item4'], dtype='object')

In [78]:
data.shape

(4, 6)

In [79]:
data.values

array([['brinjal', 20, 'cake', 25, 'Apple', 30],
       ['potato', 40, 'biscuits', 45, 'Orange', 45],
       ['onion', 35, 'candy', 30, 'banana', 60],
       ['tomato', 26, 'lollypop', 25, 'Cherry', 90]], dtype=object)

In [83]:
data

vegetables  vegetables_price    Sweets  Sweets_price  Fruits  \
item1    brinjal                20      cake            25   Apple   
item2     potato                40  biscuits            45  Orange   
item3      onion                35     candy            30  banana   
item4     tomato                26  lollypop            25  Cherry   

       Fruits_price  
item1            30  
item2            45  
item3            60  
item4            90

In [82]:
data.iloc[0]

vegetables          brinjal
vegetables_price         20
Sweets                 cake
Sweets_price             25
Fruits                Apple
Fruits_price             30
Name: item1, dtype: object

In [90]:
data.index.name='index'
data.columns.name='items name'

In [91]:
data

items name vegetables  vegetables_price    Sweets  Sweets_price  Fruits  \
index                                                                     
item1         brinjal                20      cake            25   Apple   
item2          potato                40  biscuits            45  Orange   
item3           onion                35     candy            30  banana   
item4          tomato                26  lollypop            25  Cherry   

items name  Fruits_price  
index                     
item1                 30  
item2                 45  
item3                 60  
item4                 90

# dataframe of nested dict

In [122]:
nested_dict={'one':{'in_one':10},
             'two':{'in_two':20,'in_three':30},
             'three':{'in_four':40,'in_five':50,'in_six':60}
             }
            

In [112]:
nested_dict['one']

{'1': 10}

In [103]:
nested_dict['two']

{'2': 20, '3': 30}

In [104]:
nested_dict['three']

{'4': 40, '5': 50, '6': 60}

In [123]:
nested_dict['one']['in_one']

10

In [124]:
new_data=pd.DataFrame(nested_dict)

In [125]:
new_data

one   two  three
in_one    10.0   NaN    NaN
in_two     NaN  20.0    NaN
in_three   NaN  30.0    NaN
in_four    NaN   NaN   40.0
in_five    NaN   NaN   50.0
in_six     NaN   NaN   60.0

In [126]:
new_data1=pd.DataFrame(nested_dict,index=['row1','row2','row3','row4','row5','row6'])

In [127]:
new_data1

one  two  three
row1  NaN  NaN    NaN
row2  NaN  NaN    NaN
row3  NaN  NaN    NaN
row4  NaN  NaN    NaN
row5  NaN  NaN    NaN
row6  NaN  NaN    NaN

In [129]:
new_data

one   two  three
in_one    10.0   NaN    NaN
in_two     NaN  20.0    NaN
in_three   NaN  30.0    NaN
in_four    NaN   NaN   40.0
in_five    NaN   NaN   50.0
in_six     NaN   NaN   60.0

# Transpose of a dataframe

In [130]:
new_data.T

in_one  in_two  in_three  in_four  in_five  in_six
one      10.0     NaN       NaN      NaN      NaN     NaN
two       NaN    20.0      30.0      NaN      NaN     NaN
three     NaN     NaN       NaN     40.0     50.0    60.0

In [167]:
new_frame=pd.DataFrame(np.arange(0,16).reshape(4,4),
                       index=['red','blue','yellow','violet'],
                       columns=['First','Second','Third','Fourth'])

In [168]:
new_frame

First  Second  Third  Fourth
red         0       1      2       3
blue        4       5      6       7
yellow      8       9     10      11
violet     12      13     14      15

# dropping a rows and column

In [165]:
new_frame1=new_frame.drop('violet',axis=0)

In [166]:
new_frame1

First  Second  Third  Fourth
red         0       1      2       3
blue        4       5      6       7
yellow      8       9     10      11

In [169]:
new_frame1=new_frame.drop('Second',axis=1)

In [170]:
new_frame1

First  Third  Fourth
red         0      2       3
blue        4      6       7
yellow      8     10      11
violet     12     14      15

# merging 

In [171]:
import numpy as np 
import pandas as pd 
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],                        
                     'price': [12.33,11.44,33.21,13.23,33.62]})
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'], 
                     'color': ['white','red','red','black']}) 
pd.merge(frame1,frame2)  


id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

# concatenation  in numpy

In [172]:
array1 = np.arange(9).reshape((3,3))
array2 = np.arange(9).reshape((3,3))+6
np.concatenate([array1,array2],axis=1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [174]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
print(ser1)
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
print(ser2)
ser1.combine_first(ser2)

1    0.124698
2    0.330622
3    0.371242
4    0.149184
5    0.070712
dtype: float64
2    0.081776
4    0.902270
5    0.095612
6    0.067559
dtype: float64


1    0.124698
2    0.330622
3    0.371242
4    0.149184
5    0.070712
6    0.067559
dtype: float64

# Cut funtion in pandas

In [175]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
bins = [0,25,50,75,100]
cat = pd.cut(results, bins)

In [176]:
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

# string methods

In [2]:
import pandas as pd
import numpy as np
dollars = pd.Series(['12', '-$10', '$10,000'], dtype="string")
dollars.str.replace('-$', '-')

0         12
1       -$10
2    $10,000
dtype: string

In [3]:
# We need to escape the special character (for >1 len patterns) 
dollars.str.replace(r'-\$', '-') 

0         12
1        -10
2    $10,000
dtype: string

In [4]:
dollars.str.replace('-$', '-', regex=False)

0         12
1        -10
2    $10,000
dtype: string

# Concatenation in Pandas

In [6]:
s = pd.Series(['a', 'b', 'c', 'd'], dtype="string")
s.str.cat(['A', 'B', 'C', 'D']) 

0    aA
1    bB
2    cC
3    dD
dtype: string